### ISSUE TITLE
Mod save files get completely wiped when having mutiple windows of coop open

### ISSUE THREAD

**Issue by TheMan6900** [coop-deluxe/sm64coopdx#319] opened 2024-09-14 16:41 UTC
uh yeah, this probably should be fixed lel.

**Comment by frog8412** [comment] 2024-09-14 17:03
Settings are saved when the game is closed, so opening 2nd window and then closing 1st one, then the 2nd one results in 2nd window's settings overwriting 1st window's settings

**Comment by EmeraldLoc** [comment] 2024-09-14 18:51
I know what he is taking about, however I’ve failed to reproduce it. How are you reproducing the bug?

**Comment by TheMan6900** [comment] 2024-09-14 19:19
I just had two windows open, with both connected to a private server, also with the tag gamemode applied. Did some matches then once I closed the window hosting the server. Boom! Tag save file dead.

**Comment by EmeraldLoc** [comment] 2024-09-14 19:44
Yea I’m unable to reproduce if I don’t use tag, so I don’t know the root cause. This does not happen if you use the old save system that used ConfigFile, so I assume it has to do with mIni.

**Comment by TheMan6900** [comment] 2024-09-14 19:47
the mod save file thing should be fixed in it of itself so, gonna rename it to just that until I find a clear way to do this with coop settings

**Closed** 2024-11-28 15:11 UTC
