### ISSUE TITLE
Crash when joining a sm64ex-coop server and then pressing Cancel

### ISSUE THREAD

**Issue by CrazyBoy2014** [coop-deluxe/sm64coopdx#132] opened 2024-05-02 13:44 UTC
**Describe the bug**
I don't know if it's only me, but whenever I try to join a sm64ex-coop server and press Cancel, the game crashes.

**To Reproduce**
1. Go to 'Join'
2. Enable sm64ex-coop compatibility
3. Try to join a server
4. While loading, press 'Cancel'
5. Game crashes

**Expected behavior**
I would join the server

**Screenshots**
![crash](https://github.com/coop-deluxe/sm64coopdx/assets/157886632/224f038b-70c0-450e-90c4-92997d97e249)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
N/A

**Comment by Agent-11** [comment] 2024-05-02 22:18
DirectX?

**Comment by CrazyBoy2014** [comment] 2024-05-05 16:39
Yes, DX11.

**Comment by Agent-11** [comment] 2024-05-05 17:36
Duplicate of https://github.com/coop-deluxe/sm64coopdx/issues/120

**Closed by Agent-11** 2024-05-05 17:36 UTC
